baseURL: "http://example.org/"
languageCode: 'en-us'
title: 'Poorna Gunathilaka'
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production 
    title: ExampleSite
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-programmer-mobile-app-development-flaticons-lineal-color-flat-icons.png"
        favicon16x16: "https://img.icons8.com/external-flaticons-lineal-color-flat-icons/16/000000/external-programmer-mobile-app-development-flaticons-lineal-color-flat-icons.png"
        favicon32x32: "https://img.icons8.com/external-flaticons-lineal-color-flat-icons/32/000000/external-programmer-mobile-app-development-flaticons-lineal-color-flat-icons.png"
        apple_touch_icon: "https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-programmer-mobile-app-development-flaticons-lineal-color-flat-icons.png"
        safari_pinned_tab: "https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-programmer-mobile-app-development-flaticons-lineal-color-flat-icons.png"

    label:
        text: "Home"

    profileMode:
        enabled: false 
        title: Poorna Gunathilaka
        buttons:
            - name: Posts
              url: posts

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: "Welcome to my blog!. I am Poorna Gunathilaka third year undergraduate of the Department of Computer Science University of Moratuwa."

    socialIcons:
        - name: stackoverflow
          url: "https://stackoverflow.com/users/12458945/poorna"
        - name: github
          url: "https://github.com/poorna2152"
        - name: linkedin
          url: "https://www.linkedin.com/in/poorna-gunathilaka"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/poorna2152/blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Posts
          name: Posts
          url: /posts/
          weight: 10
